#!/bin/bash
# shellcheck disable=SC2034
# shellcheck disable=SC1091
# shellcheck disable=SC2153

set -euo pipefail

# if container log level is trace:
# print commands and their arguments as they are executed
container log level eq trace && set -x

if [ "${OPENLDAP_BOOTSTRAP_PPOLICY}" = "true" ]; then

    source "/container/services/openldap-bootstrap/assets/scripts/helpers/common.sh"

    check_args "$@"

    TYPE="$1"

    if [ "${TYPE}" = "env" ]; then
        ENV_FILE="$2"

        OPENLDAP_BOOTSTRAP_PPOLICY_HASH_CLEAR_TEXT=${OPENLDAP_BOOTSTRAP_PPOLICY_HASH_CLEAR_TEXT^^}
        OPENLDAP_BOOTSTRAP_PPOLICY_USE_LOCKOUT=${OPENLDAP_BOOTSTRAP_PPOLICY_USE_LOCKOUT^^}

        OPENLDAP_BOOTSTRAP_PPOLICY_CHECK_MODULE_LDIF=""
        if [ -n "${OPENLDAP_BOOTSTRAP_PPOLICY_CHECK_MODULE}" ]; then
            OPENLDAP_BOOTSTRAP_PPOLICY_CHECK_MODULE_LDIF="olcPPolicyCheckModule: ${OPENLDAP_BOOTSTRAP_PPOLICY_CHECK_MODULE}"
        fi

        OPENLDAP_BOOTSTRAP_PPOLICY_GROUP_OU=$(get_dn_attr ou "${OPENLDAP_BOOTSTRAP_PPOLICY_GROUP_DN}")

        OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_POLICY_CN=$(get_dn_attr cn "${OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_POLICY_DN}")

        OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_ALLOW_USER_CHANGE=${OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_ALLOW_USER_CHANGE^^}
        OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_SAFE_MODIFY=${OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_SAFE_MODIFY^^}
        OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_MUST_CHANGE=${OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_MUST_CHANGE^^}
        OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_LOCKOUT=${OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_LOCKOUT^^}

        prepare_env_file "${ENV_FILE}" OPENLDAP_BOOTSTRAP_PPOLICY_HASH_CLEAR_TEXT OPENLDAP_BOOTSTRAP_PPOLICY_USE_LOCKOUT OPENLDAP_BOOTSTRAP_PPOLICY_CHECK_MODULE_LDIF OPENLDAP_BOOTSTRAP_PPOLICY_GROUP_OU OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_POLICY_CN OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_ALLOW_USER_CHANGE OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_SAFE_MODIFY OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_MUST_CHANGE OPENLDAP_BOOTSTRAP_PPOLICY_DEFAULT_LOCKOUT

    elif [ "${TYPE}" = "ldif" ]; then
        SOURCE_DIR="$2"
        OUTPUT_DIR="$3"

        prepare_ldif_files "${SOURCE_DIR}/ppolicy" "${OUTPUT_DIR}"
    fi

fi
